### ISSUE TITLE
Invalid Hobart tests

### ISSUE THREAD

**Issue by gold2718** [CESM-Development/cime_config#15]
The following test uses an unsupported FV grid on Hobart
` <test name="PEA_P1" grid="f45_g37" compset="B1850" testmods="allactive/defaultio">`

I'm not sure what resolution to change this to. We are not planning on supporting f45 (4x5) and we don't (yet?) have mapping files for f10 (10x15). Move it to f19 or f09?

**Comment by mvertens** [comment]
The right compset to use for this resolution is B1850Ws - which as a stub
wave

1850_CAM60_CLM50%BGC_CICE_POP2%ECO_MOSART_CISM2%NOEVOLVE_SWAV_BGC%BDRD

This compset is not missing any missing mapping files at f45_g37.

I think we should simply change the tests to refer to this compset instead.

**Comment by ekluzek** [comment]
@gold2718 is CAM removing support for f45_g37? CLM is going to keep f45 and we currently seem to test both f45_f45_mg37 and f45_g37, which for CLM is identical.

**Comment by mvertens** [comment]
I think my suggestion will resolve the issue that Steve is running into.

**Comment by gold2718** [comment]
Sorry, I was not clear on the problem. There are no CAM6 initial data files for f45 and we were not planning on making any. Does anyone need a CAM6 initial data file for f45?

**Comment by brian-eaton** [comment]
Historically the 4x5 resolution was used for WACCM development.  That may no longer be relevant.  Perhaps Francis can comment.

**Comment by cacraigucar** [comment]
At a previous CAM meeting, we had discussed resolutions, and had agreed that we were dropping support for 4x5.  Do we need to reconsider this decision and bring it up for discussion today?

**Comment by brian-eaton** [comment]
In that case I assume Andrew and Francis were in agreement to drop support and I don't see any need to revisit.

**Comment by fischer-ncar** [comment]
I'll replace the PEA_P1.f45_g37.B1850 with PEA_P1.f19_g16.B1850.
