### ISSUE TITLE
ADESP_TEST does not belong in allactive tests

### ISSUE THREAD

**Issue by gold2718** [CESM-Development/cime_config#17]
Test, name="PRE" grid="f19_f19_mg16" compset="ADESP_TEST" does not belong in the allactive testlist. It should be in the driver testlist.

**Comment by fischer-ncar** [comment]
@gold2718, do you want me to change the grid to g19_f19_g17?

**Comment by mvertens** [comment]
If we do change it then make sure its _mg17 NOT _g17.

**Comment by fischer-ncar** [comment]
I did do _mg17.

**Comment by fischer-ncar** [comment]
Closed via PR #18
