### ISSUE TITLE
Test in testlist with missing compset

### ISSUE THREAD

**Issue by ekluzek** [CESM-Development/cime_config#48]
There's a test in the testlist that doesn't have a corresponding compset. The closest compset is the same with the "Ws" at the end.

  <test name="IRT" grid="f19_g17" compset="B1850C4L45BGCRBPRPWs" testmods="allactive/defaultio">
    <machines>
      <machine name="bluewaters" compiler="pgi" category="prebeta"/>
      <options>
        <option name="wallclock"> 00:30 </option>
      </options>
    </machines>
  </test>

**Comment by fischer-ncar** [comment]
Fixed in #51
